# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PushPull
email: 3dmin@3dmin.org
description: > # this means to ignore newlines until "baseurl:"
  PushPull is an instrument developed as part of the 3DMIN project. This page may serve as an inspiration for you. What will you build? What will you do different? 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://3dmin.github.io/" # the base hostname & protocol for your site
twitter_username: 3dmin
github_username:  3dmin

# Build settings
markdown: kramdown

#Anpassungen
collections:
  build:
    output: true
    layout: page-build
  start:
    output: false

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  # hard_wrap: false
